# Generated by Django 4.1.1 on 2022-10-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seccion",
            options={"verbose_name_plural": "Secciones"},
        ),
    ]
