# Generated by Django 4.1.1 on 2022-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_autor_edad_autor_profecion_seccion_fecha_de_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
